FROM alpine:3.13.3

ENV SAMTOOLS_VERSION 1.12
ENV SAMTOOLS_REPO1 https://github.com/samtools/samtools/releases/download
ENV SAMTOOLS_REPO2 ${SAMTOOLS_REPO1}/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2

WORKDIR /opt
RUN apk update && \
    apk add --no-cache build-base~=0.5-r2 zlib-dev~=1.2.11-r3 bzip2-dev~=1.0.8-r1 \
                       xz-dev~=5.2.5-r0 ncurses-dev~=6.2_p20210109-r0 \
                       ca-certificates~=20191127-r5 wget~=1.21.1-r1 curl-dev~=7.76.1-r0 && \
    wget --progress=dot:giga --quiet ${SAMTOOLS_REPO2} && \
    tar -xjvf samtools-${SAMTOOLS_VERSION}.tar.bz2 && \
    cd /opt/samtools-${SAMTOOLS_VERSION} && \
    make && mv samtools /bin && rm -rf /opt/samtools* && \
    apk del build-base zlib-dev ca-certificates

LABEL org.opencontainers.image.authors="Lukas Goetz" \
      org.opencontainers.image.version=${SAMTOOLS_VERSION} \
      org.opencontainers.image.title="samtools"
